### ISSUE TITLE
cleanupOutputBeforeBuild when watching file changes

### ISSUE THREAD

**Issue by timum-viw** [symfony/webpack-encore#158] opened 2017-09-12 10:34 UTC
I'm not sure if this is wanted behaviour, but when using webpack --watch option the output folder apparently does not get cleared when recompiling after files change, even though I'm using cleanupOutputBeforeBuild. Normally the output files should get overwritten, but since I'm also using enableVersioning option I end up with a whole bunch of versioned files in my output folder.
Any thought about that?
Cheers

**Comment by Lyrkan** [comment] 2017-09-12 13:37
Hi @timum-viw,

I would guess that's caused by the fact that the [`watch` option of the `clean-webpack-plugin`](https://github.com/johnagan/clean-webpack-plugin#options-and-defaults-optional) isn't set to true when `cleanOutputBeforeBuild` is called.

There is a pending PR that'll allow to configure this plugin more easily (#152) but in the meantime you could try something like this:

```js
// webpack.config.js
const Encore = require('@symfony/webpack-encore');
const CleanWebpackPlugin = require('clean-webpack-plugin');

Encore
  .setOutputPath('build/')
  .setPublicPath('/')
  .cleanupOutputBeforeBuild()
  // ...
;

const config = Encore.getWebpackConfig();

for (const plugin of config.plugins) {
  if ((plugin instanceof CleanWebpackPlugin) && plugin.options) {
    plugin.options.watch = true;
  }
}

module.exports = config;
```

**Comment by timum-viw** [comment] 2017-09-12 15:44
sounds reasonable. the workaround seams to work for now.
Thanks!

**Comment by timum-viw** [comment] 2017-09-12 15:49
ay, I was a bit quick on the last one. seems like not all files get rebuild. so now I'm missing the files that were unchanged..
Ideas?

**Comment by Lyrkan** [comment] 2017-09-12 16:54
You're right, it seems that it can't be done using `clean-webpack-plugin`:

* https://github.com/johnagan/clean-webpack-plugin/issues/43
* https://github.com/johnagan/clean-webpack-plugin/issues/54

**Comment by stof** [comment] 2017-09-12 17:26
Well, cleaning only invalidated files is quite hard to solve actually

**Comment by weaverryan** [comment] 2017-09-12 18:22
So this is not something we can fix. If clean-webpack-plugin fixes it someday, awesome! So, I'm closing for now!

**Closed by weaverryan** 2017-09-12 18:22 UTC
