### ISSUE TITLE
Versioning hash added to images even with enableVersioning(false)

### ISSUE THREAD

**Issue by andyexeter** [symfony/webpack-encore#155] opened 2017-09-07 13:11 UTC
A version hash seems to be added to any images I reference in CSS regardless of the value passed to the `enableVersioning()` method in both production and dev environments.

I'm using the webpack config in the example here: https://symfony.com/doc/current/frontend/encore/simple-example.html with a fresh Symfony 3.3 install - The only difference being that I have explicitly disabled versioning.

**/webpack.config.js:**
```js
var Encore = require('@symfony/webpack-encore');

Encore
// directory where all compiled assets will be stored
    .setOutputPath('web/build/')

    // what's the public path to this directory (relative to your project's document root dir)
    .setPublicPath('/build')

    // empty the outputPath dir before each build
    .cleanupOutputBeforeBuild()

    // will output as web/build/app.js
    .addEntry('app', './assets/js/main.js')

    // will output as web/build/global.css
    .addStyleEntry('global', './assets/css/global.scss')

    // allow sass/scss files to be processed
    .enableSassLoader()

    // allow legacy applications to use $/jQuery as a global variable
    .autoProvidejQuery()

    //.enableSourceMaps(!Encore.isProduction())
    .enableSourceMaps(!Encore.isProduction())

    .enableVersioning(false)
;

// export the final configuration
module.exports = Encore.getWebpackConfig();
```

**/assets/css/global.scss:**
```scss
.test {
    // Uses /assets/images/doge.jpg
    background-image: url('../images/doge.jpg');
}
```

Running `yarn run encore dev` or `yarn run encore production` generates the file `/web/build/images/doge.cccfd52c.jpg` and creates:

**/web/build/css/global.css:**
```css
.test {
  background-image: url(/build/images/doge.cccfd52c.jpg);
}

```

My understanding is that `enableVersioning(true)` creates hashed filenames, so I'm not sure why `enableVersioning(false)` is creating hashed filenames for images?

I've created a repo for the test project here: https://github.com/andyexeter/encore-test

**Comment by stof** [comment] 2017-09-07 13:23
Duplicate of https://github.com/symfony/webpack-encore/issues/136.

I'm closing this issue as the discussion happens on the existing one.

**Closed by stof** 2017-09-07 13:23 UTC
