### ISSUE TITLE
How should image assets be handled?

### ISSUE THREAD

**Issue by MPLLC** [symfony/webpack-encore#85] opened 2017-07-08 00:33 UTC
I have a couple image files that are referenced by CSS.  How should I handle these with Webpack Encore, if at all?  The documentation doesn't say anything about image assets.  Can I use `addEntry`?  Or will they be automatically detected/handled if they're in a location like `/path/to/project/app/Resources/assets/images`?

It's just a bit confusing coming from using Assetic in all my old projects.

**Comment by davidmpaz** [comment] 2017-07-10 07:50
Maybe this is a duplicate of #24 ? Could you confirm @MPLLC? Work is done in that direction, not yet ready though.

**Comment by MPLLC** [comment] 2017-07-10 18:17
Ah, didn't see #24.  Yes, my question/issue is more or less the same.

**Comment by weaverryan** [comment] 2017-07-10 19:49
Closing as a duplicate - thanks for your question! It's one of our top issues to clarify for people :)

**Closed by weaverryan** 2017-07-10 19:49 UTC
