### ISSUE TITLE
Output file to big ?

### ISSUE THREAD

**Issue by xorgxx** [symfony/webpack-encore#168] opened 2017-09-28 06:24 UTC
Hi i'm trying to use webpack-encore, so far i deed install with the guide. Since that all work, but i have "entry" files css size maxi 400Ko, when i compile with webpack i get 5M "output and more.

it's normal ?
Sf3.3 / Webpack-encore last version / Npm 3.10.10 / node v6.11.3 / on windows 10 64
Thank

**Comment by xorgxx** [comment] 2017-09-28 06:49
i get in the end of my css file ```/*# sourceMappingURL=data:application/json;charset=utf-8;base64,......``` this is what put my file so big.

**Comment by javiereguiluz** [comment] 2017-09-28 06:53
Yes, source maps will make your files huge ... but they are useful ... if you use them. The recommended setting for Encore is to generate source maps only for "dev" environment, not production:

```json
Encore
    // ...

    .enableSourceMaps(!Encore.isProduction())

    // ...
;
```

**Comment by Lyrkan** [comment] 2017-09-28 07:43
Note that even if you enable source maps for the production environment they [shouldn't be inlined](https://github.com/symfony/webpack-encore/blob/master/lib/config-generator.js#L55-L58) but generated as separated files.

Since that's the intended behavior I'm closing this issue but feel free to reopen it if your source maps are also inlined in production mode.

**Closed by Lyrkan** 2017-09-28 07:43 UTC
