### ISSUE TITLE
Manifest.json changes when running --watch

### ISSUE THREAD

**Issue by crtlf** [symfony/webpack-encore#413] opened 2018-10-17 16:22 UTC
## My configuration

`webpack.config.js` :

```javascript
Encore
  .setOutputPath('web/build/')
  .setPublicPath('/build')
  .addEntry('app', './app/Resources/public/js/app.js')
  .addEntry('pdf', './app/Resources/public/js/pdf.js')
  .autoProvidejQuery()
  .cleanupOutputBeforeBuild()
  .enableBuildNotifications()
  .enableSingleRuntimeChunk()
  .enableSassLoader()
;
```

## My problem

My `app.js` entry is calling a bunch of Javascript and CSS files that uses some fonts and images. So, when I first launch 

```shell
encore dev --watch
```

a `manifest.json` is generated with all these assets (and CSS & JS of course) :

```json
{
  "build/app.css": "/build/app.css",
  "build/app.js": "/build/app.js",
  "build/pdf.css": "/build/pdf.css",
  "build/pdf.js": "/build/pdf.js",
  "build/runtime.js": "/build/runtime.js",
  "build/fonts/CLIENT_NAME-SemiBold.woff": "/build/fonts/CLIENT_NAME-SemiBold.385377d3.woff",-
  "build/fonts/CLIENT_NAME-Bold.woff": "/build/fonts/CLIENT_NAME-Bold.4545e187.woff",
  "build/fonts/CLIENT_NAME-Bold.woff2": "/build/fonts/CLIENT_NAME-Bold.c8ac6d47.woff2",
  "build/fonts/CLIENT_NAME-BoldItalic.woff": "/build/fonts/CLIENT_NAME-BoldItalic.a825f499.woff",
  "build/fonts/CLIENT_NAME-BoldItalic.woff2": "/build/fonts/CLIENT_NAME-BoldItalic.04848b65.woff2",
  "build/fonts/CLIENT_NAME-Italic.woff": "/build/fonts/CLIENT_NAME-Italic.21d054dc.woff",
  "build/fonts/CLIENT_NAME-Italic.woff2": "/build/fonts/CLIENT_NAME-Italic.d1c164b0.woff2",
  "build/fonts/CLIENT_NAME-Light.woff": "/build/fonts/CLIENT_NAME-Light.4fda3f1d.woff",
  "build/fonts/CLIENT_NAME-Light.woff2": "/build/fonts/CLIENT_NAME-Light.ee652b41.woff2",
  "build/fonts/CLIENT_NAME-LightItalic.woff": "/build/fonts/CLIENT_NAME-LightItalic.11c53fc0.woff",
  "build/fonts/CLIENT_NAME-LightItalic.woff2": "/build/fonts/CLIENT_NAME-LightItalic.0a70a14a.woff2",
  "build/fonts/CLIENT_NAME-Regular.woff": "/build/fonts/CLIENT_NAME-Regular.8ac0ee8f.woff",
  "build/fonts/CLIENT_NAME-Regular.woff2": "/build/fonts/CLIENT_NAME-Regular.58577a5c.woff2",
  "build/fonts/CLIENT_NAME-SemiBold.woff2": "/build/fonts/CLIENT_NAME-SemiBold.fcb10903.woff2",
  "build/fonts/CLIENT_NAME-SemiBoldItalic.woff": "/build/fonts/CLIENT_NAME-SemiBoldItalic.85f83e58.woff",
  "build/fonts/CLIENT_NAME-SemiBoldItalic.woff2": "/build/fonts/CLIENT_NAME-SemiBoldItalic.ff6bda0e.woff2",
  "build/images/_dots.svg": "/build/images/_dots.3e10aa7a.svg"
}
```

But if I make a modification in one of my JS or CSS file (during the watch process), the `manifest.json` deletes all the assets (fonts & images) references.

```json
{
  "build/app.css": "/build/app.css",
  "build/app.js": "/build/app.js",
  "build/pdf.css": "/build/pdf.css",
  "build/pdf.js": "/build/pdf.js",
  "build/runtime.js": "/build/runtime.js"
}
```

If I kill the watch process and relaunch it, the assets are back again.

## Questions

* First of all, is it normal ?
* I don't have enabled versionning, so why do my assets have version numbers ? (they are not regenerated)
* Is it normal to have a `manifest.json` even if I don't use versionning ? I know I have enabled it for testing, maybe that's why.

**Comment by Lyrkan** [comment] 2018-10-17 17:38
Hi @crtlf,

> First of all, is it normal ?

Definitely not!

Since you're calling `Encore.enableSingleRuntimeChunk` I'm guessing that you're using the Webpack 4 version of Encore. Is it up-to-date?

Are all of the missing files required from a CSS file or does it also happen for assets required from a JS file?

I don't know if this is related but there is this issue opened on the `manifest-weback-plugin` repository: https://github.com/danethurber/webpack-manifest-plugin/issues/144.

> I don't have enabled versionning, so why do my assets have version numbers ?

Images/fonts are always versioned by default. That wasn't always the case but not doing it caused some issues when you add two files with the same name in different directories (see: https://github.com/symfony/webpack-encore/issues/136#issuecomment-321300764)

You can change this behavior by calling [`Encore.configureFilenames`](https://github.com/symfony/webpack-encore/blob/5fcd4cb5f116c4eeeeb7212267b663dc6f0811ac/index.js#L868-L894).

> Is it normal to have a manifest.json even if I don't use versionning ? I know I have enabled it for testing, maybe that's why.

I'd say yes, even if your files are not versioned it can be useful to have that info available (for instance if you change the public path).

**Comment by Lyrkan** [comment] 2018-10-17 19:04
So... I did a quick test and was able to reproduce the problem.

It may be related to the `webpack-manifest-plugin` issue I linked in my previous comment since the workaround from that same thread seemed to work:

```js
Encore.configureManifestPlugin((options) => {
  options.seed = {};
});
```

It apparently won't be fixed in the plugin before its next major version (3.x), so I guess we could force that value in the default options set by Encore...

@crtlf Could you tell me if that also works for you?

**Comment by Lyrkan** [comment] 2018-10-18 08:33
Glad to hear it :)

I'm reopening the issue until #414 gets merged in case other people run into it.

**Closed** 2018-10-19 14:40 UTC
Labels: HasPR, bug
