### ISSUE TITLE
Add Type definitions (*.d.ts)

### ISSUE THREAD

**Issue by Eptagone** [symfony/webpack-encore#1147] opened 2022-08-28 04:26 UTC
I love this package and it would be even better if the library included the declaration file (index.d.ts) as well.
For those of us using TypeScript, it would be appreciated if we could use a `webpack.config.ts` with their type definitions.

**Comment by stof** [comment] 2022-08-28 14:08
Closing as duplicate of https://github.com/symfony/webpack-encore/issues/816

**Closed by stof** 2022-08-28 14:08 UTC
