### ISSUE TITLE
Allow sass CLI for better performance

### ISSUE THREAD

**Issue by pbowyer** [symfony/webpack-encore#1011] opened 2021-06-23 19:06 UTC
Full credit to https://github.com/snowpackjs/snowpack for this idea.

The current `sass` compiler is written in Dart (hereafter "Dart Sass"). Dart Sass's stand-alone command-line executable uses the blazing-fast Dart VM to compile stylesheets. Dart Sass is also distributed as the pure JavaScript sass package on npm, which Webpack Encore uses. The pure JS version is slower than the stand-alone executable - 9x slower for this [StackOverflow test](https://stackoverflow.com/a/56422541/119750).

Snowpack's [Sass plugin](https://github.com/snowpackjs/snowpack/tree/main/plugins/plugin-sass) allows you to install the Dart Sass command-line executable and use that instead of the npm package. The [code](https://github.com/snowpackjs/snowpack/blob/main/plugins/plugin-sass/plugin.js) is fairly straightforward.

Usually I like to quantify the change, but I haven't worked out how to benchmark the speed-up this would give me. With Webpack (Encore) my sass compilation is between 20-30 seconds on first run (which is 5+ seconds longer than when I used libsass) so any reduction is good.

Is this an addition Webpack Encore would support?

**Comment by Kocal** [comment] 2021-06-23 20:33
Hi :wave: 

This is a really interesting idea since compiling `.sass` files can be very slow sometimes.

Encore handle `.sass` files with the help of [`sass-loader`](https://github.com/webpack-contrib/sass-loader), so implementing native binary support should be done on their side and not on Encore (we alreay provide a method to configure the `sass-loader`), or just small updates...

Any optimization is important since it can reduces compilation time when developping, building your app in CI, or deploying your application in production.

**Comment by pbowyer** [comment] 2021-06-24 07:31
Thanks for the quick response.

Checking the `sass-loader` repository they have an issue for this https://github.com/webpack-contrib/sass-loader/issues/774 open since... 2019. Their code already interweaves node-sass and dart-sass throughout so adding a third way looks a nightmare.

**Comment by stof** [comment] 2021-06-24 08:47
Well, the sass team is working on embedded dart-sass, which will run the dart executable in a subprocess. And it will be exposed through the same JS API. So once this work is ready (currently it is in progress), it should be usable in sass-loader.

**Comment by leonexcc** [comment] 2022-02-15 09:22
The sass-embedded ist now usable since sass-loader version 12.5.0 (see https://github.com/webpack-contrib/sass-loader/releases/tag/v12.5.0). But Encore puts out the error message:
```
Error: Install sass (or node-sass) to use enableSassLoader()
      yarn add sass --dev
```

This can be fixed by adding ```{ name: 'sass-embedded' }``` to https://github.com/symfony/webpack-encore/blob/9e1528efbbd9db8ac734c177f2e22c71a507e60c/lib/features.js#L24

Also the library has to be activated manually:
```
.enableSassLoader((options) => {
    try {
        require.resolve('sass-embedded');
        options.implementation = 'sass-embedded';
    } catch (ignoreError) {
        // Fallback to default implementation (sass or node-sass)
    }
})
```

And there are some known bugs https://github.com/webpack-contrib/sass-loader/issues/774#issuecomment-1039253270

**Comment by leonexcc** [comment] 2022-02-17 11:28
As of version v12.6.0 of sass-loader the sass-embedded will be detected automatically and a simple ```.enableSassLoader()``` will work

**Comment by curry684** [comment] 2022-02-25 10:32
I can confirm in my case simply applying the fix to line 24 and installing `sass-embedded` improves performance by 400%. For my project this is the difference between hot reload being usable or not.

#1097 should be merged and released asap   :)

**Comment by pbowyer** [comment] 2022-02-25 10:52
@curry684 Nice results! I've tried a few times but so far can't resolve Bootstrap with either `~` or `../node_modules/...` so waiting on https://github.com/webpack-contrib/sass-loader/issues/774#issuecomment-1046014498 being resolved before I try again.

**Comment by curry684** [comment] 2022-02-25 12:14
Note that is IS usable today if you follow the guide above at https://github.com/symfony/webpack-encore/issues/1011#issuecomment-1040041930

You need to keep `sass` installed to please the validator, and if it is installed `sass-loader` will by default still prefer it over `sass-embedded`. So set `options.implementation` for now explicitly.

**Comment by stof** [comment] 2022-05-06 14:00
Closing this as `sass-embedded` is not supported by webpack-encore as one of the sass implementations and so does not trigger a warning anymore (meaning you can uninstall `sass` if you want)

**Closed by stof** 2022-05-06 14:00 UTC

**Comment by Kocal** [comment] 2022-05-06 15:02
now*
