### ISSUE TITLE
'@symfony/webpack-encore@0.30.2' is not in the npm registry.

### ISSUE THREAD

**Issue by tifed** [symfony/webpack-encore#820] opened 2020-08-06 09:52 UTC
package.json:

{
    "devDependencies": {
        "@symfony/webpack-encore": "^0.30.0",
        "core-js": "^3.0.0",
        "regenerator-runtime": "^0.13.2",
        "webpack-notifier": "^1.6.0"
    },
    "license": "UNLICENSED",
    "private": true,
    "scripts": {
        "dev-server": "encore dev-server",
        "dev": "encore dev",
        "watch": "encore dev --watch",
        "build": "encore production --progress"
    },
    "dependencies": {
        "jquery": "^3.5.1"
    }
}

npm i result

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@symfony%2fwebpack-encore - Not found
npm ERR! 404 
npm ERR! 404  '@symfony/webpack-encore@^0.30.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-08-06T09_51_20_385Z-debug.log

**Comment by jdreesen** [comment] 2020-08-06 09:56
Duplicate of #819

**Closed** 2020-08-06 10:13 UTC
