### ISSUE TITLE
`enableIntegrityHashes` and `configureFilenames` can conflict together

### ISSUE THREAD

**Issue by Kocal** [symfony/webpack-encore#1340] opened 2024-09-16 07:00 UTC
While working on #969, I've found that the `Encore.enableIntegrityHashes()` feature was doing nothing, because my `Encore.configureFilenames()` configuration:
```js
Encore.configureFilenames({
    js: '[name].js?v=[contenthash:8]',
    css: '[name].css?v=[contenthash:8]',
    assets: 'assets/[name].[ext]?v=[contenthash:8]',
})
```

Using a query-parameter to store `contenthash` instead of the filename itself, is a strategy mentioned in https://github.com/symfony/webpack-encore/issues/1266.

If I had `console.log({outputPath: webpackConfig.outputPath, file, publicPath, filePath })` below 
lines https://github.com/symfony/webpack-encore/blob/main/lib/plugins/entry-files-manifest.js#L55-L58, it outputs:
```js
{
  outputPath: '/Users/kocal/path-to-app/public/build',
  file: '/build/app.js?v=3af532f5',
  publicPath: '/build/',
  filePath: '/Users/kocal/path-to-app/public/build/app.js?v=3af532f5'
}
```

The next line `fs.existsSync(filePath)` can only returns false, because it will try to find a file explicitly named `app.js?v=3af532f5`, which... does not exist. But `app.js` file does exist!

If I remove my custom filenames formats, as expected I can see the integrity hashes in `entrypoints.json` file.

---

What should we do?

Should we check if `?` is present in the filename, and if yes, remove `?` and everything after?
Should we keep the actual behavior but log a warning instead?

**Comment by stof** [comment] 2024-09-16 13:27
Duplicate of https://github.com/symfony/webpack-encore/issues/1269

**Closed** 2024-09-16 13:28 UTC
Labels: Bug
