### ISSUE TITLE
createSharedEntry don't work as expected

### ISSUE THREAD

**Issue by lowwa132** [symfony/webpack-encore#218] opened 2017-11-28 14:20 UTC
As the [documentation](https://symfony.com/doc/current/frontend/encore/shared-entry.html) says, if we include a CSS file to be extracted in a shared entry, it will not be included anymore in the other CSS files processed.

However, bootstrap.css is still included in the generated app.css...

Here is my webpack.config.js
```
// webpack.config.js
var Encore = require('@symfony/webpack-encore');

Encore
    // the project directory where all compiled assets will be stored
    .setOutputPath('web/build/')

    // the public path used by the web server to access the previous directory
    .setPublicPath('/build')

    // will create web/build/app.js and web/build/app.css
    .addEntry('app', './assets/js/app.js')

    // this creates a 'vendor.js' file with jquery and the bootstrap JS module
    // these modules will *not* be included in page1.js or page2.js anymore
    .createSharedEntry('vendor', [
        'jquery',
        'bootstrap-sass',

        // you can also extract CSS - this will create a 'vendor.css' file
        // this CSS will *not* be included in page1.css or page2.css anymore
        'bootstrap-sass/assets/stylesheets/_bootstrap.scss'
    ])

    // allow sass/scss files to be processed
    .enableSassLoader()

    // allow legacy applications to use $/jQuery as a global variable
    .autoProvidejQuery()

    .enableSourceMaps(!Encore.isProduction())

    // empty the outputPath dir before each build
    .cleanupOutputBeforeBuild()

    // show OS notifications when builds finish/fail
    .enableBuildNotifications()

    // create hashed filenames (e.g. app.abc123.css)
    // .enableVersioning()
    .enableSassLoader(function(sassOptions) {}, {
        resolveUrlLoader: false
    })
;

// export the final configuration
module.exports = Encore.getWebpackConfig();
```
app.js
```
/* fix for https://github.com/symfony/webpack-encore/pull/54 */
global.$ = global.jQuery = require('jquery');

require('bootstrap-sass');
require('../css/global.scss');

```

global.scss
```
$icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";
$font-family-base: "Lato", sans-serif;
@import '~bootstrap-sass/assets/stylesheets/bootstrap';
@import url('https://fonts.googleapis.com/css?family=Lato:400,700,300,900');

@import '../../web/assets/css/front-v2.css';
```

package.json
```
{
  "name": "kelprof",
  "version": "1.0.0",
  "devDependencies": {
    "@symfony/webpack-encore": "^0.17.0",
    "bootstrap-sass": "^3.3.7",
    "jquery": "^3.2.1",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6",
    "webpack-notifier": "^1.5.0"
  }
}
```

**Comment by stof** [comment] 2017-11-28 15:29
I'm not sure CommonChunksPlugin works fine for CSS in combination with ExtractTextPlugin

**Comment by johnny-bit** [comment] 2018-05-03 16:08
Is there a workaround for this issue? This creates a bit of a problem when one small file could benefit from extending some class defined in framework - if trying to use sass `@extend` without importing main framework the sass compilation complains about missing identifier; if trying to use `@import` you'd get huge css file and double framework definitions...

**Comment by weaverryan** [comment] 2018-05-03 19:46
I have a feeling that the issue is not related to ExtractTextPlugin, but instead either using `@import` or Sass. I don't know for sure, but I bet one of those are confusing things.

> Plus it seems that CommonChunksPlugin got deprecated with Webpack 4 and another approach is needed.

Indeed. This may or may not help the issue - not sure yet. The chunk handling is just WAY different in Webpack 4.

**Comment by weaverryan** [comment] 2018-11-16 19:44
Closing as CommonsChunkPlugin has been replaced by the `splitChunks` functionality in Webpack 4 (latest version of Encore)

**Closed by weaverryan** 2018-11-16 19:44 UTC
