### ISSUE TITLE
 ERROR Failed to compile with 0 errors

### ISSUE THREAD

**Issue by theredled** [symfony/webpack-encore#601] opened 2019-07-05 16:31 UTC
I have 6 different JS entries, containing different files.

I'm running "`yarn encore dev`"
I get "`ERROR  Failed to compile with 0 errors`

No more details, therefore I can't fix anything at all.

My `webpack.config.js`:
```javascript
let Encore = require('@symfony/webpack-encore');

Encore
    .setOutputPath('web/build/')
    .setPublicPath('/build')
    .setManifestKeyPrefix('build/')
//-- this one is well-compiled (I think)
    .addEntry('app-vendors', './assets/app-vendors.js')
//-- those ones are all identical
    .addEntry('app-classes', './assets/app-classes.js')
    .addEntry('markable-maps-classes', './assets/markable-maps-classes.js')
    .addEntry('markable-maps-vendors', './assets/markable-maps-vendors.js')
    .addEntry('calendar-vendors', './assets/calendar-vendors.js')
    .addEntry('calendar-classes', './assets/calendar-classes.js')
    .enableSingleRuntimeChunk()
;

var config = Encore.getWebpackConfig();
config.node = { fs: 'empty' };
module.exports = config;
```

app-classes.js
```javascript
let files = [
    'classes/Foldable.js',
    'classes/HorizontalPlanning.js',
    'classes/PlanningWorkTimes.js',
    'classes/AttachmentsList.js',
    'classes/CameraModal.js',
    'classes/Affair.js',
    'classes/AffairStepsFinancialInfos.js',
    'classes/Forms.js',
    'classes/NewEventContextMenu.js',
    'classes/GroupAction.js',
    'classes/AuthRights.js',
    'functions.js',
    'init.js'
];

for (let file of files)
    require('../web/js/Business/' + file);
```

calendar-classes.js
```javascript
let files = [
    'classes/Calendars/BaseCalendar.js',
    'classes/Calendars/SingleCalendar.js',
    'classes/Calendars/SyncCalendars.js',
    'classes/Calendars/EmployeesSyncCalendars.js',
    'classes/Calendars/Planning.js',
    'classes/Calendars/RoomsSyncCalendars.js',
];

for (let file of files)
    require('../web/js/Business/' + file);
```

calendar-vendors.js
```javascript
let files = [
    'fullcalendar/fullcalendar.js',
    'fullcalendar/locale/fr.js',
];

for (let file of files)
    require('../web/js/Business/' + file);
```

Command output:
```
$ yarn encore dev
yarn run v1.16.0
$ '/Volumes/Macintosh HD Data/Users/theredled/Sites/qualispace/deploy/node_modules/.bin/encore' dev
Running webpack ...

 ERROR  Failed to compile with 0 errors                                                            17:11:12

Entrypoint app-vendors [big] = app-vendors.css app-vendors.js
Entrypoint app-classes [big] = app-classes.js
Entrypoint markable-maps-classes [big] = markable-maps-classes.js
Entrypoint markable-maps-vendors [big] = markable-maps-vendors.js
Entrypoint calendar-vendors [big] = calendar-vendors.js
Entrypoint calendar-classes [big] = calendar-classes.js
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Lyrkan** [comment] 2019-07-05 20:13
Hi @theredled,

That's probably related to #593 which is caused by the `friendly-errors-webpack-plugin` not displaying some warnings/errors.

Could you try calling `Encore.enableBuildNotifications()` to see if it displays (at least part of) the error?

And if the notification doesn't work or doesn't show anything either, the following change could help:

```diff
// webpack.config.js
const Encore = require('@symfony/webpack-encore');

Encore
    .setOutputPath('web/build/')
    .setPublicPath('/build')
    // (...)

const config = Encore.getWebpackConfig();
config.node = { fs: 'empty' };

+ // Force Webpack to display errors/warnings
+ config.stats.errors = true;
+ config.stats.warning = true;

module.exports = config;
```

**Comment by Lyrkan** [comment] 2019-08-05 14:41
Closing as a duplicate of #593

**Closed by Lyrkan** 2019-08-05 14:41 UTC
